console.log(typeof undefined)
console.log(typeof null)
console.log(typeof true)
console.log(typeof 'react')
console.log(typeof 7)
console.log(typeof { key: 'value' })
console.log(typeof function () {})
console.log(typeof SVGSymbolElement('シンボル'))
console.log(typeof 23456789456789n)
console.log(typeof Date())
